#!/usr/bin/env sh

title="Homelab status"
header="Homelab status"
timeout=10
tmp="$(mktemp -d)"
checkfile="${1:-checks.csv}"
incidentsfile="${2:-incidents.txt}"
failonoutage=false
useragent="User-Agent: Mozilla/5.0 (X11; Linux x86_64; Debian) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

command_exists(){
    if ! command -v "${1}" >/dev/null 2>&1; then
        echo >&2 "Error: ${1} missing. Please install it"
        exit 1
    fi
}

get_element(){
    echo "${2}" | awk -v col="${1}" -F',' '{gsub(/^[ \t]+|[ \t]+$/, "", $col); print $col}'
}

check(){
    ctype="${1}"
    host="${2}"
    name="${3}"
    expectedcode="${4}"

    IPv="$(echo "${ctype}" | grep -o '[46]$')"
    case "${ctype}" in
        http*)
            statuscode="$(curl -${IPv}sSkLo /dev/null -H "${useragent}" -m "${timeout}" -w "%{http_code}" "${host}" 2> "${tmp}/ko/${name}.error")";;
        ping*)
            ping -${IPv}W "${timeout}" -c 1 "${host}" >/dev/null 2>&1
            statuscode=$?
            [ "${statuscode}" -ne "${expectedcode}" ] && echo 'Host unreachable' > "${tmp}/ko/${name}.error";;
        port*)
            error="$(nc -${IPv}w "${timeout}" -zv ${host} 2>&1)"
            statuscode=$?
            [ "${statuscode}" -ne "${expectedcode}" ] && echo "${error}" > "${tmp}/ko/${name}.error";;
    esac

    # verity status and write files
    if [ "${statuscode}" -eq "${expectedcode}" ]; then
        echo "Status code: ${statuscode}" > "${tmp}/ok/${name}.status"
    else
        echo "Status code: ${statuscode}" > "${tmp}/ko/${name}.status"
    fi
    if [ -s "${tmp}/ko/${name}.error" ]; then
        sed "${tmp}/ko/${name}.error" \
          -e 's,curl: ([0-9]*) ,,' \
          -e 's,.*) failed: ,,' > "${tmp}/ko/${name}.status"
    fi
}

command_exists 'curl'
command_exists 'nc'
command_exists 'ping'
mkdir -p "${tmp}/ok" "${tmp}/ko" || exit 1

while IFS="$(printf '\n')" read -r line; do
    ctype="$(get_element 1 "${line}")"
    code="$(get_element 2 "${line}")"
    name="$(get_element 3 "${line}")"
    host="$(get_element 4 "${line}")"
    check "${ctype}" "${host}" "${name}" "${code}" &
done < "${checkfile}"
wait

cat << EOF
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>${title}</title><style>
body { font-family: segoe ui,Roboto,Oxygen-Sans,Ubuntu,Cantarell,helvetica neue,Verdana,sans-serif; }
h1 { margin-top: 30px; }
ul { padding: 0px; }
li { list-style: none; padding: .5rem; font-size: 18px; background-color: white; border-radius: 3px; box-shadow: rgba(0, 0, 0, 0.75) 0px 0px 30px -18px; }
li:not(:last-child) { margin-bottom: .5rem; }
body { background-color: #f5f8fa; }
.container { max-width: 600px; width: 100%; margin: 15px auto; }
.panel { text-align: center; padding: 1rem; border: 0px; border-radius: 3px; font-size: 20px; }
.failed-bg  { color: white; background-color: #E25D6A; }
.success-bg { color: white; background-color: #52B86A; }
.failed  { color: #E25D6A; }
.success { color: #52B86A; }
.small { font-size: 80%; }
.status { float: right; }
.incident { padding: .5rem; border-radius: 3px; box-shadow: rgba(0, 0, 0, 0.75) 0px 0px 33px -32px; border-left: 16px solid rgba(177, 177, 177, 0.2); background-color: white; }
.incident:not(:last-child) { margin-bottom: 16px; }
.incident .timestamp { font-size: 13px; color: rgb(110, 107, 107); font-weight: bold; }
.incident.bg-info { border-left: 16px solid rgba(110, 223, 246, 0.2); }
.incident.bg-success { border-left: 16px solid rgba(117, 183, 152, 0.2); }
.incident.bg-warning { border-left: 16px solid rgba(255, 218, 106, 0.2); }
.incident.bg-danger { border-left: 16px solid rgba(234, 134, 143, 0.2); }
</style></head>
<body>
<div class='container'>
<h1>${header}</h1>
EOF
outagenb="$(find "${tmp}/ko" -mindepth 1 | grep -c 'status$')"
if [ "${outagenb}" -ne 0 ]; then
    echo "<ul><li id='top_banner' class='panel failed-bg'>${outagenb} Outage(s)</li></ul>"
else
    echo "<ul><li id='top_banner' class='panel success-bg'>All Systems Operational</li></ul>"
fi
cat << EOF
<h2>Services</h2>
<ul>
EOF
for file in "${tmp}/ko/"*.status; do
    [ -e "${file}" ] || continue
    name="$(basename "${file}" | sed 's,.status$,,')"
    status="$(cat "${file}")"
    echo "<li>${name} <span class='small failed'>(${status})</span><span class='status failed'>Disrupted</span></li>"
done
for file in "${tmp}/ok/"*.status; do
    [ -e "${file}" ] || continue
    name="$(basename "${file}" | sed 's,.status$,,')"
    echo "<li>${name} <span class='status success'>Operational</span></li>"
done
cat << EOF
</ul>
<p class=small>Last check: $(date +%FT%T%z)</p>
EOF
if [ -f "${incidentsfile}" ]; then
    echo '<h2>Incidents</h2>'
    if [ -s "${incidentsfile}" ]; then
        sed 's|^\([a-z]*\)\|\(.*\)$|<div class="incident bg-\1">\2</div>|' "${incidentsfile}"
    else
        echo '<p>No incident reported yet ;)</p>'
    fi
fi
cat <<EOF
<p class=small style="text-align: right;"><a href="https://github.com/thomasjsn/tinystatus">tinystatus</a></p>
</div>
<script>
    var date1 = new Date('$(date +%FT%T%z)');
    var date2 = new Date(Date.now() - 1000 * (60 * 5));

    var dateIsOld = date2.getTime() > date1.getTime();

    if (dateIsOld === true) {
        var elements = document.querySelectorAll('.status');

        for ( var i=elements.length; i--; ) {
            elements[i].textContent = "Unknown";
            elements[i].classList.remove("success");
            elements[i].classList.add("failed");
        }

        var topBanner = document.getElementById("top_banner");
        topBanner.innerHTML = "Systems Unreachable";
        topBanner.classList.remove("success-bg");
        topBanner.classList.add("failed-bg");
    }
</script>
</body></html>
EOF

rm -r "${tmp}" 2>/dev/null
if [ "${failonoutage}" = true ]; then
    exit "${outagenb}"
fi

